# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create a new CloudFormation stack from a template
          command: |
            aws cloudformation deploy --stack-name exercise16-infrastructure-creation --template-file template.yml

workflows:
  exercise16-infrastructure_creation:
    jobs:
      - create_infrastructure
